# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-porepatrol-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # TODO nf-core: Add required software dependencies here
#  - fastqc=0.11.8
#  - multiqc=1.7
  #- nanoplot=1.24.0 installed via pip
  - porechop=0.2.3_seqan2.1.1
  #- nanofilt=2.3.0  installed via pip
# for markdown_to_html.r
  - r-markdown=0.9

  



